#!/bin/sh
# on startup the system is not quite ready when called, so lets play it safe and wait a while
sleep 6

# see if wifi network with SSID swarmhub is available
if (bcmwl escanresults | grep "swarmhub")
then
	# disable wifi and bring back up again
	ifconfig eth0 down
	bcmwl down
	bcmwl band auto
	bcmwl autocountry 1
	bcmwl up
	
	# set AP mode to 0 (parrot default is 1 for ad-hoc host)
	bcmwl ap 0
	
	# join wifi network swarmhub
	bcmwl join swarmhub
	
	# set static IP to .2 and add default gateway
	ifconfig eth0 192.168.40.2 netmask 255.255.255.0 up
	route add default gw 192.168.40.1 eth0
	
	# from the udhcpc message clip the leased IP address
	dhcpip=`udhcpc -b -i eth0 -x hostname:$(hostname) | grep "obtained" | awk '{print $3}'`
	
	# check if previous command returned a valid IP address
	if (echo $dhcpip | grep ".40.")
	then
		# set IP address according DHCP lease and print IP
		ifconfig eth0 $dhcpip netmask 255.255.255.0 up
		echo DHCP success, using IP $dhcpip
	else
		# print status and static IP
		echo DHCP failed, using static IP 192.168.40.2
	fi
else
	# print wifi status
	echo SSID not found
fi

# Telnet & adb                                                      
echo "Starting telnet & adb" | ulogger -t "NetworkUSB" -p I         
/usr/sbin/telnetd -l /bin/login.sh                                  
/usr/bin/pstart adbd
